### ISSUE TITLE
Erro de comunicação

### ISSUE THREAD

**Issue by ShidoDeMisar** [DenysXavier/WSBoletoSantander#58]
Olá pessoal boa tarde a todos!
Eu estou enfrentando o seguinte erro:

Fatal error: Uncaught Exception in /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/REGISTRO/class/ComunicadorCurlSOAP.php:25 
Stack trace: #0 /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/REGISTRO/class/BoletoSantanderServico.php(153): ComunicadorCurlSOAP->chamar('https://ymbdlb....', Array) 
#1 /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/REGISTRO/class/BoletoSantanderServico.php(58): BoletoSantanderServico->executarServico('https://ymbdlb....', Object(XMLWriter)) 
#2 /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/REGISTRO/class/BoletoSantanderServico.php(26): BoletoSantanderServico->gerarTicket(Object(Boleto)) 
#3 /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/registroBoletos.php(49): BoletoSantanderServico->solicitarTicketInclusao(Object(Boleto)) 
#4 {main} thrown in /home/storage/4/6d/8d/sgestaoescolar1/public_html/modules/BOLETOS/REGISTRO/class/ComunicadorCurlSOAP.php on line 25

Alguém consegue me ajudar com isso?

**Comment by DenysXavier** [comment]
Boa noite, @ShidoDeMisar!

Vendo apenas o que temos aqui, acredito que não dê para ajudar muito.

Aparentemente, uma Exception está sendo lançada pelo método solicitarTicketInclusao e não está sendo tratada.

Esse método está dentro de uma estrutura try-catch? Se estiver, o que vem na mensagem da Exception?
